package examen1p2_emilianourtecho;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.ActionMap;
import javax.swing.JOptionPane;

public class Libreria extends javax.swing.JFrame {

    public Libreria() {
        initComponents();
    }
    public void publicarLibro(Libros libros) {
        libro.add(libros);
    }    
    private String stringLibro(Libros libro) {
        return "Título: " + libro.getTitulo() + "\n" +
               "Autor: " + libro.getAutor() + "\n" +
               "Edición: " + libro.getEdicion() + "\n" +
               "Precio: " + libro.getPrecio() + "\n\n";
    }    

    private Libros buscarLibroParaEditar(String tipo, String nombre) {
        Referencias referencias = new Referencias();
        for (Libros libros : libro) {
            if ((tipo != null && referencias.getTipo().equals(tipo)) || 
                (nombre != null && libros.getTitulo().equals(nombre))) {
                return libros;
            }
        }
        return null;
    }    
    
    private String stringLibroE(Libros libros) {
        Referencias referencia = new Referencias();
        if (libro != null) {
            return "Título: " + libros.getTitulo() + "\n" +
                   "Autor: " + libros.getAutor() + "\n" +
                   "Tipo: " + referencia.getTipo() + "\n" +
                   "Edición: " + libros.getEdicion() + "\n" +
                   "Precio: " + libros.getPrecio() + "\n\n";
        } else {
            return "Libro no encontrado.";
        }
    }
    
    private Libros buscarLibroParaEliminar(String tipo, String nombre) {
        Referencias referencia = new Referencias();
        for (Libros libros : libro) {
            if ((tipo != null && referencia.getTipo().equals(tipo)) || 
                (nombre != null && libros.getTitulo().equals(nombre))) {
                return libros;
            }
        }
        return null;
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p_adminLog = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tf_userAdministrador = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        pf_password = new javax.swing.JPasswordField();
        b_logIn = new javax.swing.JButton();
        b_entrarUsuario = new javax.swing.JButton();
        p_adminPagina = new javax.swing.JPanel();
        crudLibros = new javax.swing.JTabbedPane();
        p_publicarLibros = new javax.swing.JPanel();
        tp_libroPublicar = new javax.swing.JTabbedPane();
        jPanel12 = new javax.swing.JPanel();
        b_publicarLibro1 = new javax.swing.JButton();
        jLabel42 = new javax.swing.JLabel();
        tf_facultadT = new javax.swing.JTextField();
        tf_cursoT = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        cb_tipoLRef = new javax.swing.JComboBox<>();
        b_publicarLibro = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        b_publicarLibro2 = new javax.swing.JButton();
        jLabel44 = new javax.swing.JLabel();
        cb_tipoLFiccion = new javax.swing.JComboBox<>();
        jPanel15 = new javax.swing.JPanel();
        b_publicarLibro3 = new javax.swing.JButton();
        jLabel45 = new javax.swing.JLabel();
        cb_tipoLNoFiccion = new javax.swing.JComboBox<>();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        tf_tituloP = new javax.swing.JTextField();
        tf_autorP = new javax.swing.JTextField();
        ff_precioP = new javax.swing.JFormattedTextField();
        p_listarLibros = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        cb_tipoListar = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_listarL = new javax.swing.JTextArea();
        p_editarLibros = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        cb_tipoEditarLibros = new javax.swing.JComboBox<>();
        jLabel33 = new javax.swing.JLabel();
        cb_libroEditarLibros = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        ta_editarL = new javax.swing.JTextArea();
        jLabel34 = new javax.swing.JLabel();
        tf_titulo = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        tf_autor = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        ff_precioEditar = new javax.swing.JFormattedTextField();
        b_editarLibro = new javax.swing.JButton();
        p_eliminarLibros = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        cb_tipoEliminarLibros = new javax.swing.JComboBox<>();
        jLabel38 = new javax.swing.JLabel();
        cb_libroEliminarLibros1 = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        ta_eliminarL = new javax.swing.JTextArea();
        b_eliminar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        p_usuarioPagina = new javax.swing.JPanel();
        tb_usuarioPanel = new javax.swing.JTabbedPane();
        p_devolverLibros = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        p_comprarLibros = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        b_back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        p_adminLog.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Administrador Log In");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("User Administrador: ");

        tf_userAdministrador.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Password: ");

        pf_password.setBackground(new java.awt.Color(255, 255, 255));
        pf_password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pf_passwordMousePressed(evt);
            }
        });

        b_logIn.setBackground(new java.awt.Color(204, 203, 204));
        b_logIn.setForeground(new java.awt.Color(0, 0, 0));
        b_logIn.setText("Log In Administrador");
        b_logIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_logInMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b_logInMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                b_logInMouseExited(evt);
            }
        });
        b_logIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_logInActionPerformed(evt);
            }
        });

        b_entrarUsuario.setBackground(new java.awt.Color(204, 204, 204));
        b_entrarUsuario.setForeground(new java.awt.Color(0, 0, 0));
        b_entrarUsuario.setText("Entrar como Usuario");
        b_entrarUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_entrarUsuarioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b_entrarUsuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                b_entrarUsuarioMouseExited(evt);
            }
        });
        b_entrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_entrarUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p_adminLogLayout = new javax.swing.GroupLayout(p_adminLog);
        p_adminLog.setLayout(p_adminLogLayout);
        p_adminLogLayout.setHorizontalGroup(
            p_adminLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_adminLogLayout.createSequentialGroup()
                .addGap(213, 213, 213)
                .addGroup(p_adminLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(b_logIn)
                    .addGroup(p_adminLogLayout.createSequentialGroup()
                        .addGroup(p_adminLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(p_adminLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_userAdministrador)
                            .addComponent(pf_password, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(221, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_adminLogLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(p_adminLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_adminLogLayout.createSequentialGroup()
                        .addComponent(b_entrarUsuario)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_adminLogLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(276, 276, 276))))
        );
        p_adminLogLayout.setVerticalGroup(
            p_adminLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_adminLogLayout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(jLabel1)
                .addGap(46, 46, 46)
                .addGroup(p_adminLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_userAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(p_adminLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(pf_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(b_logIn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                .addComponent(b_entrarUsuario)
                .addContainerGap())
        );

        getContentPane().add(p_adminLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 440));

        p_adminPagina.setBackground(new java.awt.Color(204, 204, 204));
        p_adminPagina.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        crudLibros.setBackground(new java.awt.Color(204, 204, 204));
        crudLibros.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        crudLibros.setForeground(new java.awt.Color(0, 0, 0));

        p_publicarLibros.setBackground(new java.awt.Color(204, 204, 204));
        p_publicarLibros.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 204, 255), 1, true));

        tp_libroPublicar.setBackground(new java.awt.Color(204, 204, 204));
        tp_libroPublicar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 204, 255), 1, true));
        tp_libroPublicar.setForeground(new java.awt.Color(0, 0, 0));

        jPanel12.setBackground(new java.awt.Color(204, 204, 204));

        b_publicarLibro1.setBackground(new java.awt.Color(204, 204, 204));
        b_publicarLibro1.setForeground(new java.awt.Color(0, 0, 0));
        b_publicarLibro1.setText("Publicar Libro");
        b_publicarLibro1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b_publicarLibro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_publicarLibro1ActionPerformed(evt);
            }
        });

        jLabel42.setForeground(new java.awt.Color(0, 0, 0));
        jLabel42.setText("Facultad:");

        tf_facultadT.setBackground(new java.awt.Color(255, 255, 255));
        tf_facultadT.setForeground(new java.awt.Color(0, 0, 0));

        tf_cursoT.setBackground(new java.awt.Color(255, 255, 255));
        tf_cursoT.setForeground(new java.awt.Color(0, 0, 0));

        jLabel43.setForeground(new java.awt.Color(0, 0, 0));
        jLabel43.setText("Curso:");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(349, Short.MAX_VALUE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel42)
                    .addComponent(jLabel43))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tf_cursoT)
                    .addComponent(tf_facultadT, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(b_publicarLibro1)
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(b_publicarLibro1)
                .addContainerGap())
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel43)
                    .addComponent(tf_cursoT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel42)
                    .addComponent(tf_facultadT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        tp_libroPublicar.addTab("Libro de Texto", jPanel12);

        jPanel13.setBackground(new java.awt.Color(204, 204, 204));

        jLabel30.setForeground(new java.awt.Color(0, 0, 0));
        jLabel30.setText("Tipo:");

        cb_tipoLRef.setBackground(new java.awt.Color(204, 204, 204));
        cb_tipoLRef.setForeground(new java.awt.Color(0, 0, 0));
        cb_tipoLRef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_tipoLRefActionPerformed(evt);
            }
        });

        b_publicarLibro.setBackground(new java.awt.Color(204, 204, 204));
        b_publicarLibro.setForeground(new java.awt.Color(0, 0, 0));
        b_publicarLibro.setText("Publicar Libro");
        b_publicarLibro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb_tipoLRef, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(346, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(b_publicarLibro)
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(cb_tipoLRef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(b_publicarLibro)
                .addContainerGap())
        );

        tp_libroPublicar.addTab("Libro de Referencia", jPanel13);

        jPanel14.setBackground(new java.awt.Color(204, 204, 204));

        b_publicarLibro2.setBackground(new java.awt.Color(204, 204, 204));
        b_publicarLibro2.setForeground(new java.awt.Color(0, 0, 0));
        b_publicarLibro2.setText("Publicar Libro");
        b_publicarLibro2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel44.setForeground(new java.awt.Color(0, 0, 0));
        jLabel44.setText("Tipo:");

        cb_tipoLFiccion.setBackground(new java.awt.Color(204, 204, 204));
        cb_tipoLFiccion.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap(346, Short.MAX_VALUE)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                        .addComponent(b_publicarLibro2)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                        .addComponent(jLabel44)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb_tipoLFiccion, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(144, 144, 144))))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel44)
                    .addComponent(cb_tipoLFiccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(b_publicarLibro2)
                .addContainerGap())
        );

        tp_libroPublicar.addTab("Libro de Ficcion", jPanel14);

        jPanel15.setBackground(new java.awt.Color(204, 204, 204));

        b_publicarLibro3.setBackground(new java.awt.Color(204, 204, 204));
        b_publicarLibro3.setForeground(new java.awt.Color(0, 0, 0));
        b_publicarLibro3.setText("Publicar Libro");
        b_publicarLibro3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel45.setForeground(new java.awt.Color(0, 0, 0));
        jLabel45.setText("Tipo:");

        cb_tipoLNoFiccion.setBackground(new java.awt.Color(204, 204, 204));
        cb_tipoLNoFiccion.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addContainerGap(637, Short.MAX_VALUE)
                .addComponent(b_publicarLibro3)
                .addContainerGap())
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(jLabel45)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb_tipoLNoFiccion, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel45)
                    .addComponent(cb_tipoLNoFiccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(b_publicarLibro3)
                .addContainerGap())
        );

        tp_libroPublicar.addTab("Libro de No Ficcion", jPanel15);

        jLabel39.setForeground(new java.awt.Color(0, 0, 0));
        jLabel39.setText("Titulo:");

        jLabel40.setForeground(new java.awt.Color(0, 0, 0));
        jLabel40.setText("Autor:");

        jLabel41.setForeground(new java.awt.Color(0, 0, 0));
        jLabel41.setText("Precio:");

        tf_tituloP.setBackground(new java.awt.Color(255, 255, 255));
        tf_tituloP.setForeground(new java.awt.Color(0, 0, 0));
        tf_tituloP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_tituloPActionPerformed(evt);
            }
        });

        tf_autorP.setBackground(new java.awt.Color(255, 255, 255));
        tf_autorP.setForeground(new java.awt.Color(0, 0, 0));

        ff_precioP.setBackground(new java.awt.Color(255, 255, 255));
        ff_precioP.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout p_publicarLibrosLayout = new javax.swing.GroupLayout(p_publicarLibros);
        p_publicarLibros.setLayout(p_publicarLibrosLayout);
        p_publicarLibrosLayout.setHorizontalGroup(
            p_publicarLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tp_libroPublicar)
            .addGroup(p_publicarLibrosLayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addGroup(p_publicarLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel41)
                    .addComponent(jLabel40)
                    .addComponent(jLabel39))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p_publicarLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tf_tituloP)
                    .addComponent(tf_autorP, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                    .addComponent(ff_precioP))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        p_publicarLibrosLayout.setVerticalGroup(
            p_publicarLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_publicarLibrosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p_publicarLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(tf_tituloP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(p_publicarLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel40)
                    .addComponent(tf_autorP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(p_publicarLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel41)
                    .addComponent(ff_precioP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(tp_libroPublicar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        crudLibros.addTab("Publicar Libro", p_publicarLibros);

        p_listarLibros.setBackground(new java.awt.Color(204, 204, 204));

        jLabel31.setForeground(new java.awt.Color(0, 0, 0));
        jLabel31.setText("Tipo:");

        cb_tipoListar.setBackground(new java.awt.Color(204, 204, 204));
        cb_tipoListar.setForeground(new java.awt.Color(0, 0, 0));
        cb_tipoListar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Titulo", "Libro de Texto", "Libro de Referencia", "Libro de Ficcion", "Libro de No Ficcion" }));
        cb_tipoListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_tipoListarActionPerformed(evt);
            }
        });

        ta_listarL.setBackground(new java.awt.Color(255, 255, 255));
        ta_listarL.setColumns(20);
        ta_listarL.setForeground(new java.awt.Color(0, 0, 0));
        ta_listarL.setRows(5);
        jScrollPane1.setViewportView(ta_listarL);

        javax.swing.GroupLayout p_listarLibrosLayout = new javax.swing.GroupLayout(p_listarLibros);
        p_listarLibros.setLayout(p_listarLibrosLayout);
        p_listarLibrosLayout.setHorizontalGroup(
            p_listarLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_listarLibrosLayout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(jLabel31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb_tipoListar, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(350, Short.MAX_VALUE))
            .addGroup(p_listarLibrosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        p_listarLibrosLayout.setVerticalGroup(
            p_listarLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_listarLibrosLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(p_listarLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(cb_tipoListar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                .addContainerGap())
        );

        crudLibros.addTab("Listar Libros", p_listarLibros);

        p_editarLibros.setBackground(new java.awt.Color(204, 204, 204));

        jLabel32.setForeground(new java.awt.Color(0, 0, 0));
        jLabel32.setText("Tipo:");

        cb_tipoEditarLibros.setBackground(new java.awt.Color(204, 204, 204));
        cb_tipoEditarLibros.setForeground(new java.awt.Color(0, 0, 0));
        cb_tipoEditarLibros.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Titulo", "Libro de Texto", "Libro de Referencia", "Libro de Ficcion", "Libro de No Ficcion" }));

        jLabel33.setForeground(new java.awt.Color(0, 0, 0));
        jLabel33.setText("Libro:");

        cb_libroEditarLibros.setBackground(new java.awt.Color(204, 204, 204));
        cb_libroEditarLibros.setForeground(new java.awt.Color(0, 0, 0));
        cb_libroEditarLibros.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Titulo", "Libro de Texto", "Libro de Referencia", "Libro de Ficcion", "Libro de No Ficcion" }));

        ta_editarL.setBackground(new java.awt.Color(255, 255, 255));
        ta_editarL.setColumns(20);
        ta_editarL.setForeground(new java.awt.Color(0, 0, 0));
        ta_editarL.setRows(5);
        jScrollPane2.setViewportView(ta_editarL);

        jLabel34.setForeground(new java.awt.Color(0, 0, 0));
        jLabel34.setText("Titulo: ");

        tf_titulo.setBackground(new java.awt.Color(255, 255, 255));
        tf_titulo.setForeground(new java.awt.Color(0, 0, 0));

        jLabel35.setForeground(new java.awt.Color(0, 0, 0));
        jLabel35.setText("Autor: ");

        tf_autor.setBackground(new java.awt.Color(255, 255, 255));
        tf_autor.setForeground(new java.awt.Color(0, 0, 0));

        jLabel36.setForeground(new java.awt.Color(0, 0, 0));
        jLabel36.setText("Precio: ");

        ff_precioEditar.setBackground(new java.awt.Color(255, 255, 255));
        ff_precioEditar.setForeground(new java.awt.Color(0, 0, 0));

        b_editarLibro.setBackground(new java.awt.Color(204, 204, 204));
        b_editarLibro.setForeground(new java.awt.Color(0, 0, 0));
        b_editarLibro.setText("Editar Libros");
        b_editarLibro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b_editarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_editarLibroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p_editarLibrosLayout = new javax.swing.GroupLayout(p_editarLibros);
        p_editarLibros.setLayout(p_editarLibrosLayout);
        p_editarLibrosLayout.setHorizontalGroup(
            p_editarLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_editarLibrosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p_editarLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(p_editarLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(p_editarLibrosLayout.createSequentialGroup()
                            .addComponent(jLabel33)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cb_libroEditarLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(p_editarLibrosLayout.createSequentialGroup()
                            .addComponent(jLabel32)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cb_tipoEditarLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(p_editarLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p_editarLibrosLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(p_editarLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(p_editarLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(p_editarLibrosLayout.createSequentialGroup()
                                    .addComponent(jLabel34)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tf_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(p_editarLibrosLayout.createSequentialGroup()
                                    .addComponent(jLabel35)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tf_autor, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(p_editarLibrosLayout.createSequentialGroup()
                                .addComponent(jLabel36)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ff_precioEditar)))
                        .addContainerGap(215, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_editarLibrosLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(b_editarLibro)
                        .addContainerGap())))
        );
        p_editarLibrosLayout.setVerticalGroup(
            p_editarLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_editarLibrosLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(p_editarLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(cb_tipoEditarLibros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(p_editarLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(cb_libroEditarLibros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(p_editarLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(p_editarLibrosLayout.createSequentialGroup()
                        .addGroup(p_editarLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel34)
                            .addComponent(tf_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(p_editarLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel35)
                            .addComponent(tf_autor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(p_editarLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel36)
                            .addComponent(ff_precioEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                        .addComponent(b_editarLibro)))
                .addContainerGap())
        );

        crudLibros.addTab("Editar Libros", p_editarLibros);

        p_eliminarLibros.setBackground(new java.awt.Color(204, 204, 204));

        jLabel37.setForeground(new java.awt.Color(0, 0, 0));
        jLabel37.setText("Tipo:");

        cb_tipoEliminarLibros.setBackground(new java.awt.Color(204, 204, 204));
        cb_tipoEliminarLibros.setForeground(new java.awt.Color(0, 0, 0));
        cb_tipoEliminarLibros.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Titulo", "Libro de Texto", "Libro de Referencia", "Libro de Ficcion", "Libro de No Ficcion" }));

        jLabel38.setForeground(new java.awt.Color(0, 0, 0));
        jLabel38.setText("Libro:");

        cb_libroEliminarLibros1.setBackground(new java.awt.Color(204, 204, 204));
        cb_libroEliminarLibros1.setForeground(new java.awt.Color(0, 0, 0));
        cb_libroEliminarLibros1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Titulo", "Libro de Texto", "Libro de Referencia", "Libro de Ficcion", "Libro de No Ficcion" }));

        ta_eliminarL.setBackground(new java.awt.Color(255, 255, 255));
        ta_eliminarL.setColumns(20);
        ta_eliminarL.setForeground(new java.awt.Color(0, 0, 0));
        ta_eliminarL.setRows(5);
        jScrollPane3.setViewportView(ta_eliminarL);

        b_eliminar.setBackground(new java.awt.Color(204, 204, 204));
        b_eliminar.setForeground(new java.awt.Color(0, 0, 0));
        b_eliminar.setText("Eliminar Libros");
        b_eliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_eliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p_eliminarLibrosLayout = new javax.swing.GroupLayout(p_eliminarLibros);
        p_eliminarLibros.setLayout(p_eliminarLibrosLayout);
        p_eliminarLibrosLayout.setHorizontalGroup(
            p_eliminarLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_eliminarLibrosLayout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addGroup(p_eliminarLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p_eliminarLibrosLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 234, Short.MAX_VALUE)
                        .addComponent(b_eliminar))
                    .addGroup(p_eliminarLibrosLayout.createSequentialGroup()
                        .addComponent(jLabel38)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb_libroEliminarLibros1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(p_eliminarLibrosLayout.createSequentialGroup()
                        .addComponent(jLabel37)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb_tipoEliminarLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        p_eliminarLibrosLayout.setVerticalGroup(
            p_eliminarLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_eliminarLibrosLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(p_eliminarLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(b_eliminar)
                    .addGroup(p_eliminarLibrosLayout.createSequentialGroup()
                        .addGroup(p_eliminarLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel37)
                            .addComponent(cb_tipoEliminarLibros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(p_eliminarLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel38)
                            .addComponent(cb_libroEliminarLibros1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        crudLibros.addTab("Eliminar Libros", p_eliminarLibros);

        p_adminPagina.add(crudLibros, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 56, -1, -1));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setForeground(new java.awt.Color(215, 211, 222));

        jButton4.setBackground(new java.awt.Color(204, 204, 204));
        jButton4.setForeground(new java.awt.Color(0, 0, 0));
        jButton4.setText("back");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton4)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jButton4)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        p_adminPagina.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 60));

        getContentPane().add(p_adminPagina, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 350));

        p_usuarioPagina.setBackground(new java.awt.Color(215, 211, 222));
        p_usuarioPagina.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tb_usuarioPanel.setBackground(new java.awt.Color(204, 204, 204));
        tb_usuarioPanel.setForeground(new java.awt.Color(0, 0, 0));

        p_devolverLibros.setBackground(new java.awt.Color(204, 204, 204));

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Comprar Libro");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Libro:");

        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Tipo:");

        jComboBox1.setBackground(new java.awt.Color(204, 204, 204));

        jComboBox2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Transaccion");

        jLabel28.setForeground(new java.awt.Color(0, 0, 0));
        jLabel28.setText("Saldo de Usuario: ");

        jTextArea1.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setForeground(new java.awt.Color(0, 0, 0));
        jTextArea1.setRows(5);
        jScrollPane4.setViewportView(jTextArea1);

        jTextArea3.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea3.setColumns(20);
        jTextArea3.setForeground(new java.awt.Color(0, 0, 0));
        jTextArea3.setRows(5);
        jScrollPane6.setViewportView(jTextArea3);

        javax.swing.GroupLayout p_devolverLibrosLayout = new javax.swing.GroupLayout(p_devolverLibros);
        p_devolverLibros.setLayout(p_devolverLibrosLayout);
        p_devolverLibrosLayout.setHorizontalGroup(
            p_devolverLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_devolverLibrosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p_devolverLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p_devolverLibrosLayout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addGroup(p_devolverLibrosLayout.createSequentialGroup()
                        .addGroup(p_devolverLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(p_devolverLibrosLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(p_devolverLibrosLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel16))
                        .addGap(0, 174, Short.MAX_VALUE))
                    .addComponent(jScrollPane6))
                .addContainerGap())
        );
        p_devolverLibrosLayout.setVerticalGroup(
            p_devolverLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_devolverLibrosLayout.createSequentialGroup()
                .addGroup(p_devolverLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p_devolverLibrosLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(p_devolverLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(p_devolverLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(p_devolverLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jLabel28)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_devolverLibrosLayout.createSequentialGroup()
                        .addContainerGap(108, Short.MAX_VALUE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        tb_usuarioPanel.addTab("Comprar Libro", p_devolverLibros);

        p_comprarLibros.setBackground(new java.awt.Color(204, 204, 204));

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Devolver Libro");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("Tipo:");

        jComboBox3.setBackground(new java.awt.Color(204, 204, 204));

        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("Libro:");

        jComboBox4.setBackground(new java.awt.Color(204, 204, 204));

        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setText("Transaccion");

        jLabel29.setForeground(new java.awt.Color(0, 0, 0));
        jLabel29.setText("Saldo de Usuario: ");

        jTextArea2.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea2.setColumns(20);
        jTextArea2.setForeground(new java.awt.Color(0, 0, 0));
        jTextArea2.setRows(5);
        jScrollPane5.setViewportView(jTextArea2);

        jTextArea4.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea4.setColumns(20);
        jTextArea4.setForeground(new java.awt.Color(0, 0, 0));
        jTextArea4.setRows(5);
        jScrollPane7.setViewportView(jTextArea4);

        javax.swing.GroupLayout p_comprarLibrosLayout = new javax.swing.GroupLayout(p_comprarLibros);
        p_comprarLibros.setLayout(p_comprarLibrosLayout);
        p_comprarLibrosLayout.setHorizontalGroup(
            p_comprarLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_comprarLibrosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p_comprarLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p_comprarLibrosLayout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(p_comprarLibrosLayout.createSequentialGroup()
                        .addGroup(p_comprarLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(p_comprarLibrosLayout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(p_comprarLibrosLayout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel22))
                        .addGap(0, 174, Short.MAX_VALUE))
                    .addComponent(jScrollPane7))
                .addContainerGap())
        );
        p_comprarLibrosLayout.setVerticalGroup(
            p_comprarLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_comprarLibrosLayout.createSequentialGroup()
                .addGroup(p_comprarLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_comprarLibrosLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(p_comprarLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(p_comprarLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(p_comprarLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jLabel29)))
                    .addGroup(p_comprarLibrosLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jScrollPane5)))
                .addContainerGap())
        );

        tb_usuarioPanel.addTab("Devolver Libro", p_comprarLibros);

        p_usuarioPagina.add(tb_usuarioPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 41, 750, 410));

        jPanel1.setBackground(new java.awt.Color(215, 211, 222));

        b_back.setBackground(new java.awt.Color(215, 211, 222));
        b_back.setForeground(new java.awt.Color(0, 0, 0));
        b_back.setText("back");
        b_back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(b_back)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(b_back)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        p_usuarioPagina.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(p_usuarioPagina, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_logInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_logInMouseClicked
        crudLibros.setSelectedIndex(0);
    }//GEN-LAST:event_b_logInMouseClicked

    private void b_logInMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_logInMouseEntered
        b_logIn.setBackground(Color.black);
        b_logIn.setForeground(Color.gray);
    }//GEN-LAST:event_b_logInMouseEntered

    private void b_logInMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_logInMouseExited
        b_logIn.setBackground(Color.gray);
        b_logIn.setForeground(Color.black);
    }//GEN-LAST:event_b_logInMouseExited

    private void b_entrarUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_entrarUsuarioMouseClicked
        tb_usuarioPanel.setSelectedIndex(0);
    }//GEN-LAST:event_b_entrarUsuarioMouseClicked

    private void b_entrarUsuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_entrarUsuarioMouseEntered
        b_entrarUsuario.setBackground(Color.black);
        b_entrarUsuario.setForeground(Color.gray);        
    }//GEN-LAST:event_b_entrarUsuarioMouseEntered

    private void b_entrarUsuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_entrarUsuarioMouseExited
        b_entrarUsuario.setBackground(Color.gray);
        b_entrarUsuario.setForeground(Color.black);        
    }//GEN-LAST:event_b_entrarUsuarioMouseExited

    private void pf_passwordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pf_passwordMousePressed
        pf_password.setText("");
        
    }//GEN-LAST:event_pf_passwordMousePressed

    private void b_logInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_logInActionPerformed
        if (tf_userAdministrador.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Porfavor llene la casilla de usuario");
        }else if(pf_password.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Porfavor llene la casilla del password");
        }else if(tf_userAdministrador.getText().contains("lib123") && pf_password.getText().contains("321lib")){
            p_adminPagina.setVisible(true);
            p_adminLog.setVisible(false);
            p_usuarioPagina.setVisible(false);
            
        }else{
            JOptionPane.showConfirmDialog(null, "Nombre de usario o password incorrectas");
        }
    }//GEN-LAST:event_b_logInActionPerformed

    private void b_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_backActionPerformed
        p_usuarioPagina.setVisible(false);
        p_adminPagina.setVisible(false);
        p_adminLog.setVisible(true);
    }//GEN-LAST:event_b_backActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        p_usuarioPagina.setVisible(false);
        p_adminPagina.setVisible(false);
        p_adminLog.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void b_entrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_entrarUsuarioActionPerformed
        p_usuarioPagina.setVisible(true);
        p_adminPagina.setVisible(false);
        p_adminLog.setVisible(false);
    }//GEN-LAST:event_b_entrarUsuarioActionPerformed

    private void tf_tituloPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_tituloPActionPerformed
        String titulo = tf_tituloP.getText();
        if (!titulo.isEmpty()) {
            Libros libros = new Libros();
                        
        }
    }//GEN-LAST:event_tf_tituloPActionPerformed

    private void b_publicarLibro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_publicarLibro1ActionPerformed
        String autor = tf_autorP.getText();
        String titulo = tf_autorP.getText();
        double precio = Double.parseDouble(ff_precioP.getText());
        int libroGuard = tp_libroPublicar.getSelectedIndex();
        
        switch(libroGuard){
            case 0:
                String curso = tf_cursoT.getText();
                String facultad = tf_facultadT.getText();
                Texto libroT = new Texto();
                publicarLibro(libroT);

                break;
            case 1:
                String referncias = (String) cb_tipoLRef.getSelectedItem();
                Referencias libroR = new Referencias();
                publicarLibro(libroR);
                break;
            case 2:
                String ficcion = (String) cb_tipoLFiccion.getSelectedItem();
                Referencias libroF = new Referencias();
                publicarLibro(libroF);
                break;
            case 3:
                String noFiccion = (String) cb_tipoLNoFiccion.getSelectedItem();
                Referencias libroNF = new Referencias();
                publicarLibro(libroNF);
                break;
        }
    }//GEN-LAST:event_b_publicarLibro1ActionPerformed

    private void cb_tipoLRefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_tipoLRefActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_tipoLRefActionPerformed

    private void cb_tipoListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_tipoListarActionPerformed
        String tipoSeleccionado = (String) cb_tipoListar.getSelectedItem();

        // Lógica para listar libros según el tipo seleccionado
        StringBuilder resultado = new StringBuilder();

        for (Libros libros : libro) {
            // Comprobar el tipo de libro y agregar al resultado
            if (libros instanceof Texto && tipoSeleccionado.equals("Libro de Texto")) {
                resultado.append(stringLibro(libros));
            } else if (libros instanceof Referencias && tipoSeleccionado.equals("Libro de Referencia")) {
                resultado.append(stringLibro(libros));
            } else if (libros instanceof Referencias && tipoSeleccionado.equals("Libro de Ficción")) {
                resultado.append(stringLibro(libros));
            } else if (libros instanceof Referencias && tipoSeleccionado.equals("Libro de No Ficción")) {
                resultado.append(stringLibro(libros));
            }
        }
        ta_listarL.setText(resultado.toString());        
    }//GEN-LAST:event_cb_tipoListarActionPerformed

    private void b_editarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_editarLibroActionPerformed
        String tipoSeleccionado = (String) cb_tipoEditarLibros.getSelectedItem();
        String nombreSeleccionado = (String) cb_libroEditarLibros.getSelectedItem();
        Libros libroEditar = buscarLibroParaEditar(tipoSeleccionado, nombreSeleccionado);
        ta_editarL.setText(stringLibroE(libroEditar));
        tf_titulo.setEditable(true);
        tf_autor.setEditable(true);
        ff_precioEditar.setEditable(true);        
    }//GEN-LAST:event_b_editarLibroActionPerformed

    private void b_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_eliminarActionPerformed
        String tipoSeleccionado = (String) cb_tipoEliminarLibros.getSelectedItem();
        String nombreSeleccionado = (String) cb_libroEliminarLibros1.getSelectedItem();

        Libros libroEliminar = buscarLibroParaEliminar(tipoSeleccionado, nombreSeleccionado);
        ta_eliminarL.setText(stringLibro(libroEliminar));
        int confirmacion = JOptionPane.showConfirmDialog(this, "¿Estás seguro de que deseas eliminar este libro?", "Confirmar Eliminación", JOptionPane.YES_NO_OPTION);
        if (confirmacion == JOptionPane.YES_OPTION) {
            if (libroEliminar != null) {
                libro.remove(libroEliminar);
                JOptionPane.showMessageDialog(this, "Libro eliminado exitosamente.", "Eliminación Exitosa", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Libro no encontrado.", "Error", JOptionPane.ERROR_MESSAGE);
            }
            ta_eliminarL.setText("");
            cb_tipoEliminarLibros.setSelectedIndex(0);
            cb_libroEliminarLibros1.setSelectedIndex(0);
        }        
    }//GEN-LAST:event_b_eliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Libreria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Libreria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Libreria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Libreria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Libreria().setVisible(true);
            }
        });
    }

    
    ArrayList<Libros> libro = new ArrayList();
    ArrayList<Texto> text = new ArrayList();
    ArrayList<Referencias> referncia = new ArrayList();
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_back;
    private javax.swing.JButton b_editarLibro;
    private javax.swing.JButton b_eliminar;
    private javax.swing.JButton b_entrarUsuario;
    private javax.swing.JButton b_logIn;
    private javax.swing.JButton b_publicarLibro;
    private javax.swing.JButton b_publicarLibro1;
    private javax.swing.JButton b_publicarLibro2;
    private javax.swing.JButton b_publicarLibro3;
    private javax.swing.JComboBox<String> cb_libroEditarLibros;
    private javax.swing.JComboBox<String> cb_libroEliminarLibros1;
    private javax.swing.JComboBox<String> cb_tipoEditarLibros;
    private javax.swing.JComboBox<String> cb_tipoEliminarLibros;
    private javax.swing.JComboBox<String> cb_tipoLFiccion;
    private javax.swing.JComboBox<String> cb_tipoLNoFiccion;
    private javax.swing.JComboBox<String> cb_tipoLRef;
    private javax.swing.JComboBox<String> cb_tipoListar;
    private javax.swing.JTabbedPane crudLibros;
    private javax.swing.JFormattedTextField ff_precioEditar;
    private javax.swing.JFormattedTextField ff_precioP;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JPanel p_adminLog;
    private javax.swing.JPanel p_adminPagina;
    private javax.swing.JPanel p_comprarLibros;
    private javax.swing.JPanel p_devolverLibros;
    private javax.swing.JPanel p_editarLibros;
    private javax.swing.JPanel p_eliminarLibros;
    private javax.swing.JPanel p_listarLibros;
    private javax.swing.JPanel p_publicarLibros;
    private javax.swing.JPanel p_usuarioPagina;
    private javax.swing.JPasswordField pf_password;
    private javax.swing.JTextArea ta_editarL;
    private javax.swing.JTextArea ta_eliminarL;
    private javax.swing.JTextArea ta_listarL;
    private javax.swing.JTabbedPane tb_usuarioPanel;
    private javax.swing.JTextField tf_autor;
    private javax.swing.JTextField tf_autorP;
    private javax.swing.JTextField tf_cursoT;
    private javax.swing.JTextField tf_facultadT;
    private javax.swing.JTextField tf_titulo;
    private javax.swing.JTextField tf_tituloP;
    private javax.swing.JTextField tf_userAdministrador;
    private javax.swing.JTabbedPane tp_libroPublicar;
    // End of variables declaration//GEN-END:variables
}
